version: '3.8'

services:
  api:
    container_name: quizzes_api
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh entrypoint.sh
    depends_on:
      - db

  db:
    container_name: quizzes_db
    image: postgres:14.1-alpine
    volumes:
      - pg_data_bets:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=quizzes_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

volumes:
  pg_data_bets: