# Generated by Django 4.1 on 2022-10-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quizinvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizinvite',
            options={'verbose_name': 'Quiz Invite', 'verbose_name_plural': 'Quiz Invites'},
        ),
        migrations.AddField(
            model_name='quizinvite',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'sent'), (2, 'accepted'), (3, 'rejected')], null=True, verbose_name='status'),
        ),
    ]
