# Generated by Django 4.1 on 2022-10-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_participants'),
        ('users', '0003_alter_quizinvite_options_quizinvite_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizInvite',
            new_name='QuizInvitation',
        ),
        migrations.AlterModelOptions(
            name='quizinvitation',
            options={'verbose_name': 'Quiz Invitation', 'verbose_name_plural': 'Quiz Invitations'},
        ),
    ]
