# Generated by Django 4.1 on 2022-10-05 13:29

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("is_finished", models.BooleanField(default=False, verbose_name="is_finished")),
                ("is_successful", models.BooleanField(default=False, verbose_name="is_successful")),
            ],
            options={
                "verbose_name": "Attempt",
                "verbose_name_plural": "Attempts",
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(default=False, verbose_name="is_correct")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attempt Answer",
                "verbose_name_plural": "Attempt Answers",
            },
        ),
    ]
