# Generated by Django 4.1 on 2022-10-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quizzes", "0001_initial"),
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptanswer",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="quizzes.answer"
            ),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="attempts.attempt"
            ),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="quizzes.question"
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="quizzes.quiz"
            ),
        ),
    ]
