# Generated by Django 4.1 on 2022-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_attemptanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptanswer',
            name='modified',
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
