# Generated by Django 4.1 on 2022-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_attemptanswer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='is_correct'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='is_correct'),
        ),
    ]
