# Generated by Django 4.1 on 2022-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_attempt_is_finished_attempt_is_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='is_finished'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_successful',
            field=models.BooleanField(default=False, verbose_name='is_successful'),
        ),
    ]
